
name: Run Playbook
# Controls when the workflow will run
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_playbook:
    runs-on: ubuntu-20.04
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v3
          with:
           fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
          
        - name: Install dependencies Including Ansible
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi

        - name: Get changed files
          id: changed-files
          uses: tj-actions/changed-files@v29.0.2
          with:
           files: |
            **/requirements/*.txt
        
        - name: Run playbook for all changed files
          run: | 
           for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
             fileSource=$(realpath -e $file)
             fileName=$(basename $file .txt)
             ansible-playbook ansible/virtualenv.yaml --extra-vars "file=$fileName source=$fileSource"
           done

